### ISSUE TITLE
Set and get methods for MPI communicator

### ISSUE THREAD

**Issue by ocaisa** [E-CAM/jobqueue_features#10]
For the MPI tasks introduced in #9, we need a way to `set` the communicator when starting dask and then provide a `get` method for use by the tasks. The current behaviour ultimately relies on `MPI_COMM_WORLD` but there is no reason we can't be more flexible than this.

**Comment by ocaisa** [comment]
@AdamWlodarczyk Is this the right way to do this?
```
task_mpi_communicator = None

def set_task_mpi_communicator(comm=None):
    global task_mpi_communicator
    
    if comm is None:
        from mpi4py import MPI

        comm = MPI.COMM_WORLD
    task_mpi_communicator = comm.Dup()

def get_task_mpi_communicator()
    global task_mpi_communicator
    if task_mpi_communicator is None:
        raise ImplementationError("MPI communicator 'task_mpi_communicator' has not been set")
    return task_mpi_communicator
```

**Comment by ocaisa** [comment]
Implementing this would potentially allow us to create nested communicators, for example we could request 80 nodes from the system and start 4 workers with 20 nodes each.

**Comment by AdamWlodarczyk** [comment]
How about this:
```
from mpi4py import MPI
TASK_MPI_COMMUNICATOR = MPI.COMM_WORLD

def set_task_mpi_communicator(comm):
    global TASK_MPI_COMMUNICATOR
    TASK_MPI_COMMUNICATOR = comm.Dup()

def get_task_mpi_communicator():
    return TASK_MPI_COMMUNICATOR
```
With that we can use ```TASK_MPI_COMMUNICATOR```  as default global with getter function and if the one wants to change this value, uses the ```set_task_mpi_communicator``` function.
The trick is to always use get and set methods since importing ```TASK_MPI_COMMUNICATOR``` to another module and changing it with ```set``` affects on the global in imported module but not on the imported  ```TASK_MPI_COMMUNICATOR``` :smiling_imp: 

Maybe the reset function would be also handful?
Something like:
```
from mpi4py import MPI

__DEFAULT_MPI_COMM = MPI.COMM_WORLD
__TASK_MPI_COMM = MPI.COMM_WORLD

def get_task_comm():
     return __TASK_MPI_COMM

def set_task_comm(comm):
    global __TASK_COMM
    __TASK_COMM = comm.Dup()

def reset_task_comm():
    global __TASK_COMM
    __TASK_COMM = __DEFAULT_MPI_COMM
```
