### ISSUE TITLE
Not up to date with use of nprocs and nthreads

### ISSUE THREAD

**Issue by ocaisa** [E-CAM/jobqueue_features#28]
Dask/jobqueue uses `nprocs` and `nthreads` to indicate how to use CPU resources on the node, we are not up to date with this.

**Comment by AdamWlodarczyk** [comment]
Could you elaborate that issue? The `Job` superclass takes `processes` and `cores` parameters. The `--nprocs` is assigned according to `processes` and `--nthreads` according to `int(cores / processes)`

**Comment by ocaisa** [comment]
I think I was wrong in my understanding of this
