### ISSUE TITLE
Incorrect options in template

### ISSUE THREAD

**Issue by ocaisa** [E-CAM/jobqueue_features#30]
There seems to be an issue with our value for `_command_template` and/or our configuration file, it doesn't seem to correctly set the `name` and also doesn't pick up on the yaml settings for `interface` (I had to manually add the kwarg to get the command line below):
```
DEBUG:Replaced command template
	/usr/local/software/jureca/Stages/Devel-2019a/software/Python/3.6.8-GCCcore-8.3.0/bin/python -m distributed.cli.dask_worker tcp://10.80.32.31:35141 --nthreads 1 --memory-limit 125.00GB --name name --no-nanny --death-timeout 15 --local-directory /tmp --interface ib0
with
	srun /usr/local/software/jureca/Stages/Devel-2019a/software/Python/3.6.8-GCCcore-8.3.0/bin/python -m jobqueue_features.cli.mpi_dask_worker tcp://10.80.32.31:35141 --nthreads 1 --memory-limit 125.00GB --name name --no-nanny --death-timeout 15 --local-directory /tmp --interface ib0
in jobscript
```

**Comment by AdamWlodarczyk** [comment]
The problem (edit: probably) lays [here](https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/core.py#L506). I will override this property in our `CustomSLURMJob`.

**Comment by AdamWlodarczyk** [comment]
As for lack of `interface` - [here](https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/core.py#L175) the `interface` parameter is checked against `None` value but in our tests we pass the empty string `""` in kwargs. If we set it as `None` then it correctly gets the `ib0` value from config... **but** the question is which interface should be passed in tests or how to control it? If given interface is invalid (let's say we there is no `ib0` interface) then what interface should we pass? The first valid one?

**Comment by ocaisa** [comment]
I can't reproduce the `interface` problem now...not sure what where it came from. On JURECA, we *have* to use `ib0`, since the eth0 interfaces are not accessible from the compute nodes.

**Comment by AdamWlodarczyk** [comment]
If you pass `""` as interface then job script will not mention the interface. If the value would be a `None` then dask gets the interface from config file which in our case would be `ib0`. The problem lays in testing configurations - in the real world usage with SLURM there should be such interface, but on local machines probably will not. I suggest using some function which returns valid interface for tests.
