### ISSUE TITLE
Reusing an mpi slurm cluster

### ISSUE THREAD

**Issue by srmnitc** [E-CAM/jobqueue_features#40]
A different question here: I created a custom slurm cluster and created an mpi task and ran a small lammps job on the custom cluster. Now after the job is finished, I want to submit a normal job, lets say squaring each element of an array to the same cluster. In this case, it seems that this operation is done element by element. Is there a way to then run a normal job on the custom cluster?

I will add the code and results in a bit, I am waiting for space on the cluster to rerun the tests and give you some more detailed code.

**Comment by ocaisa** [comment]
You wouldn't want to do this because Dask is only aware of (and manages) one processor on the cluster, it is MPI that exposes the rest of the resources. For the task you mention, it is better (as in less wasteful) to create another cluster that is not in MPI mode and use that.

**Comment by srmnitc** [comment]
@ocaisa thanks!
