### ISSUE TITLE
Citing?

### ISSUE THREAD

**Issue by dwhswenson** [E-CAM/jobqueue_features#68]
Peter Bolhuis and I are writing a review on developments in path sampling, and, in mentioning the OPS/dask combination, I was hoping to cite jobqueue-features. Any special citation (want to upload to Zenodo?) or should I lump it in with the Dask citation (as with Dask-Jobqueue)?

**Comment by ocaisa** [comment]
For the time being we have this I guess? https://zenodo.org/record/3527643

I gave you maintainer access, maybe that is enough if you want to do a Zenodo release?

**Comment by dwhswenson** [comment]
We're about to send it in, and we're using the whitepaper Zenodo that @ocaisa recommended above. If, in the future, there's a better source to cite (next whitepaper?), it would probably be good to link that here and/or in the docs/readme.

Closing. Thanks!
