### ISSUE TITLE
Look for and reuse the previous notebooks

### ISSUE THREAD

**Issue by AdamWlodarczyk** [E-CAM/jobqueue_features#74]
Find out if the stuff from last year can be useful for the upcoming event.

**Comment by AdamWlodarczyk** [comment]
It turned out that those notebooks are available here: https://github.com/E-CAM/jobqueue_features_workshop_materials

**Comment by ocaisa** [comment]
Hmm, I'm not sure what the right move is now, those notebooks are useful. Maybe it is a better idea to put the tutorial in a separate repo and have docker clone that repo to use as the lab directory

**Comment by ocaisa** [comment]
Fixed in #85
